ITEMS = q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12

all: $(ITEMS)

%: %.c
	gcc $< -o $*

1: q1
	./q1

2: q2
	./q2

3: q3
	./q3

4: q4
	./q4

5: q5
	./q5

6: q6
	./q6

7: q7
	./q7

8: q8
	./q8

9: q9
	./q9

10: q10
	./q10

11: q11
	./q11

12: q12
	./q12

clean:
	rm $(ITEMS)